main
# Dependabot configuration for SovereigntyOS
# Automatically keeps dependencies up to date

version: 2
updates:
  # Enable version updates for npm packages

version: 2
updates:
chore/security-hardening
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
main
      day: "monday"
      time: "04:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 10
    reviewers:
      - "deedk822-lang"
    assignees:
      - "deedk822-lang"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group related updates together
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "@types/jest"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "eslint*"
          - "prettier"
      security:
        patterns:
          - "helmet*"
          - "cors*"
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions

    open-pull-requests-limit: 10

chore/security-hardening
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
main
      day: "monday"
      time: "04:30"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 5
    reviewers:
      - "deedk822-lang"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "ci/cd"
      - "automated"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 3
    reviewers:
      - "deedk822-lang"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "docker"
      - "automated"

 chore/security-hardening
