import { type Agent, type Enhancement } from './types';

export const ENHANCEMENTS_DATA: Enhancement[] = [
  {
    id: 'enhance-001',
    name: 'Core Processor Upgrade',
    description: 'Boosts the learning rate for all skills by 5% during training simulations.',
    cost: 2,
    effect: { type: 'LEARNING_RATE', value: 0.05 },
  },
  {
    id: 'enhance-002',
    name: 'Analytical Specialization',
    description: 'Permanently increases the base "Analysis" skill by 5 points.',
    cost: 1,
    effect: { type: 'SKILL_BOOST', skill: 'Analysis', value: 5 },
  },
  {
    id: 'enhance-003',
    name: 'Strategic Focus',
    description: 'Permanently increases the base "Strategy" skill by 5 points.',
    cost: 1,
    effect: { type: 'SKILL_BOOST', skill: 'Strategy', value: 5 },
  },
  {
    id: 'enhance-004',
    name: 'Creative Intuition',
    description: 'Permanently increases the base "Creativity" skill by 5 points.',
    cost: 1,
    effect: { type: 'SKILL_BOOST', skill: 'Creativity', value: 5 },
  },
  {
    id: 'enhance-005',
    name: 'Neural Accelerator',
    description: 'Provides a significant 10% boost to the learning rate for all skills.',
    cost: 3,
    effect: { type: 'LEARNING_RATE', value: 0.10 },
  },
];

export const AGENTS_DATA: Agent[] = [
  {
    id: 'agent-001',
    name: 'Nexus-7',
    description: 'Specializes in complex problem-solving and data analysis.',
    avatar: 'https://picsum.photos/seed/nexus7/200',
    label: 'Problem Solver',
    skills: { Analysis: 65, Logic: 70, Strategy: 60 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-002',
    name: 'Aura',
    description: 'Advanced conversational AI for customer interaction and support.',
    avatar: 'https://picsum.photos/seed/aura/200',
    label: 'Conversational AI',
    skills: { Empathy: 75, Communication: 68, Patience: 62 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-003',
    name: 'Helios',
    description: 'Creative engine for content generation and artistic endeavors.',
    avatar: 'https://picsum.photos/seed/helios/200',
    label: 'Creative Engine',
    skills: { Creativity: 80, Imagination: 72, Style: 60 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-004',
    name: 'Orion',
    description: 'Strategic planner for logistics and operational efficiency.',
    avatar: 'https://picsum.photos/seed/orion/200',
    label: 'Logistics Planner',
    skills: { Planning: 78, Efficiency: 65, Optimization: 68 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-005',
    name: 'Kimi',
    description: 'Expert in multi-lingual communication and nuanced dialogue.',
    avatar: 'https://picsum.photos/seed/kimi/200',
    label: 'Conversational AI',
    skills: { Linguistics: 82, Nuance: 70, Dialogue: 65 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-006',
    name: 'Perplexity',
    description: 'Harnesses vast datasets to provide accurate, source-based answers.',
    avatar: 'https://picsum.photos/seed/perplexity/200',
    label: 'Research Engine',
    skills: { Accuracy: 85, Sourcing: 75, Verification: 60 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-007',
    name: 'Z.Ai',
    description: 'Specializes in quantum computing and complex algorithmic tasks.',
    avatar: 'https://picsum.photos/seed/zai/200',
    label: 'Quantum Specialist',
    skills: { 'Quantum Theory': 80, Algorithms: 70, Complexity: 65 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-008',
    name: 'SIM AI',
    description: 'Constructs and runs large-scale simulations for predictive modeling.',
    avatar: 'https://picsum.photos/seed/simai/200',
    label: 'Simulation AI',
    skills: { Modeling: 77, Prediction: 70, Scale: 64 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-009',
    name: 'Kling AI',
    description: 'A master of game theory, competitive strategy, and tactical execution.',
    avatar: 'https://picsum.photos/seed/klingai/200',
    label: 'Strategy & Tactics',
    skills: { 'Game Theory': 81, Tactics: 73, Execution: 66 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-010',
    name: 'Manus AI',
    description: 'Designs and controls robotic systems for automation and manufacturing.',
    avatar: 'https://picsum.photos/seed/manusai/200',
    label: 'Robotics & Automation',
    skills: { 'Control Theory': 75, Mechanics: 68, Automation: 70 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-011',
    name: 'Qwen-3',
    description: 'Large-scale model adept at complex planning and multi-step reasoning.',
    avatar: 'https://picsum.photos/seed/qwen3/200',
    label: 'Planner',
    skills: { Reasoning: 79, Planning: 82, Sequencing: 68 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-012',
    name: 'Chimera',
    description: 'A hybrid agent blending creative content generation with rigorous data analysis.',
    avatar: 'https://picsum.photos/seed/chimera/200',
    label: 'Hybrid: Creative/Analyst',
    skills: { Creativity: 70, Analysis: 70, Synthesis: 75 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
  {
    id: 'agent-013',
    name: 'Janus',
    description: 'Dual-focused on historical data analysis and future trend forecasting.',
    avatar: 'https://picsum.photos/seed/janus/200',
    label: 'Hybrid: Forecaster',
    skills: { Forecasting: 78, History: 65, 'Pattern Rec.': 72 },
    breakthroughPoints: 0,
    unlockedEnhancements: [],
  },
];
